### ISSUE TITLE
endless horse

### ISSUE THREAD

**Issue by richfitz** [sckott/cowsay#32]
See http://endless.horse (who knew there was a `.horse` tld?)

Trick is working out how to simulate endless scrolling without being deeply annoying.

**Comment by sckott** [comment]
s/https/http

**Comment by richfitz** [comment]
So sad

**Comment by sckott** [comment]
https://gist.github.com/audy/9802831ee97a6fa61ac0

**Comment by sckott** [comment]
good enough, closing
