### ISSUE TITLE
iheartquotes api is down 

### ISSUE THREAD

**Issue by sckott** [sckott/cowsay#35]
https://travis-ci.org/sckott/cowsay/builds/64363216#L1212

**Comment by udaiarora** [comment]
Were you able to contact ihearquotes? Their website seems to be redirecting to some other site as well.

**Comment by sckott** [comment]
No, didn't try. Do you see any contact info anywhere?

**Comment by udaiarora** [comment]
Negative. Prob gonna switch to "theysaidso"

**Comment by sckott** [comment]
good idea

**Comment by sckott** [comment]
I think it's gone for good. maybe we can replace it with some other quote API

**Comment by Zhuinden** [comment]
Yeah it's dead

**Comment by sckott** [comment]
thanks
