### ISSUE TITLE
why is animals object not exported?

### ISSUE THREAD

**Issue by stevenpollack** [sckott/cowsay#37]
subject says it all.

I would love to just be able to import `animals` with `::`, as opposed to `:::` (which has build checks yell at me).

An easy way to allow people (like my lazy self) to get `cowsay` animals without having to use `:::` would be something like
```
#' @export
getAnimal <- function(animalName) {
    return(animals[animalName])
}
```

Just an idea, though...

**Comment by sckott** [comment]
thanks for your message @stevenpollack 

I guess this use case if if you don't necessarily want to do a typical cowsay message/warning/stop, but do something else with the animal. Sounds good.

**Comment by stevenpollack** [comment]
Yeah, that's precisely it: I wanted to integrate the cool `cowsay` ASCII into my own project, but not necessary use `cowsay::say`...

**Comment by sckott** [comment]
okay, try now

**Comment by stevenpollack** [comment]
When I import `cowsay` into my package, then install it (via `devtools::install`), I get the following error:
```
Note: the specification for S3 class “AsIs” in package ‘RJSONIO’ seems equivalent to one from package ‘jsonlite’: not turning on duplicate class definitions for this class.
```
Any idea that what's about?

**Comment by sckott** [comment]
great!
