### ISSUE TITLE
Weird RJSONIO-jsonlite error upon import

### ISSUE THREAD

**Issue by stevenpollack** [sckott/cowsay#38]
When I import `cowsay` into my package, then install it (via `devtools::install`), I get the following error:
```
Note: the specification for S3 class “AsIs” in package ‘RJSONIO’ seems equivalent to one from package ‘jsonlite’: not turning on duplicate class definitions for this class.
```
Any idea that what's about?

**Comment by sckott** [comment]
right, just a second

**Comment by sckott** [comment]
@stevenpollack okay, now using `jsonlite` instead of `RJSONIO`. try again see if you get the same error

**Comment by stevenpollack** [comment]
Totally fixed it. Way to go, dude. :+1: :+1:

**Comment by sckott** [comment]
:smile_cat:
