### ISSUE TITLE
retrojunkie.com is offline

### ISSUE THREAD

**Issue by apjanke** [sckott/cowsay#43]
The www.retrojunkie.com site, linked from the README under "Where to find ASCII animal art", is offline. The hostname isn't even resolving, so it looks like it may be gone for good. Should the link be removed from the README?

```
$ ping retrojunkie.com
ping: cannot resolve retrojunkie.com: Unknown host
$ ping www.retrojunkie.com
ping: cannot resolve www.retrojunkie.com: Unknown host
```

**Comment by sckott** [comment]
Yep, should be removed. thanks
