### ISSUE TITLE
Distinct project name, like "Rcowsay"?

### ISSUE THREAD

**Issue by apjanke** [sckott/cowsay#44]
Any chance of renaming this project and repo to "rcowsay" or something similar, to distinguish it from the [original command line (Perl) cowsay](http://web.archive.org/web/20071026043648/http://www.nog.net/~tony/warez/cowsay.shtml) and implementations in other languages, like the Java-based [ricksbrown/cowsay](https://github.com/ricksbrown/cowsay)? It would make discussing them a bit easier, and would make contributing to multiple cowsay projects easier with GitHub forks. Right now if I fork both projects, one of them ends up as "apjanke/cowsay-1", which isn't very descriptive.

**Comment by sckott** [comment]
Thanks for the idea. This pkg has been around for a while though, so i probably won't rename it. Though I'll leave this open and see if others agrees with you, if enough do we can change it
