### ISSUE TITLE
Standardize the spacing above animals' speech bubbles?

### ISSUE THREAD

**Issue by aedobbyn** [sckott/cowsay#68]
Spacing above the text differs depending on the animal, e.g. [cat](https://github.com/bgreenwell/cowsay/blob/master/R/animals.r#L326) vs. [chicken](https://github.com/sckott/cowsay/blob/master/R/animals.r#L16).

I think the cat spacing is preferable because there's a smaller gap, but fine as long as they're standard imo. (Removing the "Colors cannot be applied in this environment :( Try using a terminal or RStudio." line in the reprex below for simplicity.)

``` r
library(cowsay)

say(by = "cat")
#> 
#>  -------------- 
#> Hello world! 
#>  --------------
#>     \
#>       \
#>         \
#>             |\___/|
#>           ==) ^Y^ (==
#>             \  ^  /
#>              )=*=(
#>             /     \
#>             |     |
#>            /| | | |\
#>            \| | |_|/\
#>       jgs  //_// ___/
#>                \_)
#> 

say(by = "chicken")
#> 
#> 
#>  ----- 
#> Hello world! 
#>  ------ 
#>     \   
#>      \
#>          _
#>        _/ }
#>       `>' \
#>       `|   \
#>        |   /'-.     .-.
#>         \'     ';`--' .'
#>          \'.    `'-./
#>           '.`-..-;`
#>             `;-..'
#>             _| _|
#>             /` /` [nosig]
#> 
```

<sup>Created on 2019-01-23 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by sckott** [comment]
good catch!

**Comment by aedobbyn** [comment]
Thanks! Are you on board with standardizing to cat spacing?

**Comment by sckott** [comment]
done in #69
