### ISSUE TITLE
vignette build warning on cran

### ISSUE THREAD

**Issue by sckott** [sckott/cowsay#75]
https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-gcc/cowsay-00check.html
https://www.r-project.org/nosvn/R.check/r-release-linux-x86_64/cowsay-00check.html

@aedobbyn getting warnings on cran checks - during vignette build its saying multicolor is not available. doesn't really make sense since its in suggests here, and all binaries seem to be avail. for multicolor on cran. 

probably wait a few days and see if those warnings go away

**Comment by aedobbyn** [comment]
cool -- looks fine now I think?

**Comment by sckott** [comment]
yeah seems good now, nevermind :)

**Comment by aedobbyn** [comment]
okay!
