### ISSUE TITLE
[feature request] appimage

### ISSUE THREAD

**Issue by FalsePhilosopher** [sckott/cowsay#83]
This has great prank potential in portable form :)

**Comment by sckott** [comment]
what is appimage?

**Comment by FalsePhilosopher** [comment]
@sckott AppImage is a format for distributing portable software on Linux without needing superuser permissions to install the application. It tries also to allow Linux distribution-agnostic binary software deployment for application developers, also called upstream packaging. https://appimage.org/ With it being packaged into an appimage cowsay is just a matter of "./cowsay.appimage say('helloworld')" on any linux distro.

**Comment by sckott** [comment]
hmmm, but cowsay is already available as a shell command https://github.com/tnalpgge/rank-amateur-cowsay so i imagine that would be better for a linux cli interface than this

**Comment by FalsePhilosopher** [comment]
@sckott True and is one of the first packages I install when I distro hop or upgrade distros. But cowsay does not come preinstalled on most linux distros. To leave a unicorn saying you should lock your screen before you leave on somebodies machine would require root access to install cowsay, or to just launch an appimage of cowsay. With an appimage you can cowsay on any distro any time without root to install anything. We could leave funny messages on any linux machine with an appimage.

**Comment by sckott** [comment]
okay, i see, i dont have time to invest in this. i dont understand if its something done in this repo or done elsewhere. if it is a minimal impact on this repo you could send a PR

**Comment by FalsePhilosopher** [comment]
@sckott You set up a ubuntu 18.04 vm as that's the oldest supported version of ubuntu and use linuxdeployqt to package the libraries and executable as an appimage. There's plenty of resources for appimages here https://github.com/AppImage/awesome-appimage
